### ISSUE TITLE
Error when trying to download a version

### ISSUE THREAD

**Issue by rueckstiess** [imlucas/mongodb-version-manager#14]
Haven't investigated it further... but here's the stacktrace.

```
$ m 3.0.0-rc5

/usr/local/lib/node_modules/mongodb-version-manager/node_modules/progress/lib/node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^
RangeError: Invalid array length
    at ProgressBar.render (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/progress/lib/node-progress.js:131:14)
    at ProgressBar.tick (/usr/local/lib/node_modules/mongodb-version-manager/node_modules/progress/lib/node-progress.js:86:8)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/mongodb-version-manager/lib/download.js:44:17)
    at IncomingMessage.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (_stream_readable.js:764:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
```

**Comment by imlucas** [comment]
Ah yes.  Need to add support for rc's that were 2.8 but are now 3.0.  We should automatically fall through eg `m 3.0.0-rc0` -> `download 2.8.0-rc0`.
